name: GitHub Page example

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Build the example
        run: |
          npm i
          cd example
          npm i
          npm run css:build
          npm run build

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./example/dist
